---
- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - name: mkdir backup
      file: path=/home/isucon/backup/ state=directory
    - name: mkdir repos
      file: path=/home/isucon/repos/ state=directory
    - name: clean mlucon_proto.git
      file: path=/home/isucon/repos/mlucon_proto.git state=absent
    - name: clone repos
      git:
        repo=https://github.com/mofumofuchan/mlucon-proto.git
        dest=/home/isucon/repos/mlucon_proto.git
    - name: clone python repo
      git:
        repo=https://github.com/mofumofuchan/mlucon-proto-python.git
        dest=/home/isucon/repos/mlucon_proto.git/webapp/python
    - name: remove .git
      file: path=/home/isucon/repos/mlucon_proto.git/.git state=absent
    - name: clean ansible
      file: path=/home/isucon/repos/mlucon_proto.git/ansible state=absent
    - name: clean benchmarker
      file: path=/home/isucon/repos/mlucon_proto.git/benchmarker state=absent
    - name: clean e2etest
      file: path=/home/isucon/repos/mlucon_proto.git/e2etest state=absent
    - name: clean portal
      file: path=/home/isucon/repos/mlucon_proto.git/portal state=absent
    - name: clean provisioning
      file: path=/home/isucon/repos/mlucon_proto.git/provisioning state=absent
    - name: clean provisioning
      file: path=/home/isucon/repos/mlucon_proto.git/README.md state=absent
    - name: clean python webapp git
      file: path=/home/isucon/repos/mlucon_proto.git/webapp/python/.git state=absent
    - name: git init
      shell: "cd /home/isucon/repos/mlucon_proto.git/ && git init && git add . && git config --global user.email 'test@example.com' && git config --global user.name 'admin' && git commit -m 'Initial commit'"
    - name: create working copy
      git:
        repo=file:///home/isucon/repos/mlucon_proto.git
        dest=/home/isucon/mlucon_proto
        update=yes
    - name: create working copy
      git:
        repo=file:///home/isucon/repos/mlucon_proto.git
        dest=/home/isucon/mlucon_proto
        update=yes
