- hosts: guests:extras
  become: yes
  tasks:
    - name: download features
      get_url: url=https://github.com/mofumofuchan/mlucon-proto/releases/download/img2/features.tar.gz dest=/home/isucon/mlucon_proto/webapp/ml/features.tar.gz checksum=md5:24fe2e239f36d1d92869d9c87101bfeb
      register: features
    - name: unarvhice features
      unarchive:
        src: /home/isucon/mlucon_proto/webapp/ml/features.tar.gz
        dest: /home/isucon/mlucon_proto/webapp/ml
        remote_src: yes
      when: features.changed
    #- name: remove features archive
    #  file: path=/home/isucon/mlucon_proto/webapp/ml/features.tar.gz state=absent
    #  when: features.changed
    - name: download VGG16 pre-trained model weight
      get_url url=https://github.com/mofumofuchan/mlucon-proto/releases/download/img2/VGG_ILSVRC_16_layers.npz dest=/home/isucon/mlucon_proto/webapp/ml/VGG_ILSVRC_16_layers.npz checksum=md5:3a8f9e4405350bda32582f8ba5033db2
    - name: ml install
      shell: cd /home/isucon/mlucon_proto/webapp/ml; bash -lc "/home/isucon/.local/python3/bin/pip install -r requirements.freeze"

- hosts: guests:extras
  become: yes
  tasks:
    - name: ml (systemd)
      copy: src=../files/etc/systemd/system/isu-ml.service dest=/etc/systemd/system/isu-ml.service owner=root mode=644
    - name: start ml service
      service: name=isu-ml state=started enabled=true
